server:
  port: "{cipher}1094924401633dd7f7fdd045c3a92add66d6620c81acf81d3f0a91c4c4cefe78"

spring:
  datasource:
    write:
      jdbc-url: ENC(uHfawtUzRveylgRhG7BWGBAaEWobwF8jBEB0L4BH5WMr54tKkllkcqA+U9dnfQWMwJexrc8JMYwmDPWr4TEyXFZJee2vcOEw7iimx5bS6A9Dhj2YtIpJeMbKHlbimgGJ6wLTT7EwHtK8SpQMKwEOGkydM7uQQsD9kubSTYyPq7OgoI+6sMomHxagRUsUaQ+l8ERn+1sJpUbYakLmU2YPRg==)
      username: ENC(Ydlj5D9yyJdWaSYQHj/GYK3nCdklXxtuU/ALkWl1SJZ7NDfUu2PuzV+67KalstqR)
      password: ENC(TtcHzUHJUVhI0LDkHYshd00NtjQmzVLX70slD3YHUVrByDnQ7bEZjbqPdYClRLVS)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(uYgtLpVT1PZnT/liujZG17CwmIBaxqIp+AGiVeWGPBHjaC7oq/TidiKcjOcPTg5EYLwkTmsuZQi55m8z2f0useXRs4axF82emmUUPuilGe+Au9+9GiFRCudgf9hmZyi+efZ9fe6eUKihnyckvlqcoZ0WUqRAqFG11ySuCcy7iEIw8TdBbdzDSDDr0h5hquoS/yPEHDZieeG6VGBxEAYXBg==)
      username: ENC(QV3AJXEuKMWAaYY3erRSGYdICJhVjqEGhayZwgdEH4Uiud7GJyLrgpDB3OPEk+Ic)
      password: ENC(MLn1YpR+HRfF4nlIGJVfXC/xLZ0L207W0reGpjW6wIDnGTVooVprHltPiBDms5RG)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ENC(qavhWLSDDt98nTldWjokT0tJga64ME1kbMCVD4QOc/KQQm69C1uTwA5E1TMPCyex+/2dk0VpMJAQOKkH/s/odw==)
      port: ENC(T/JL4jKuxWsTgqcVu7uiF0VijJFiDi4zq7Pjduf2Spr76ETUKlrU24S2i7znl1qj)
      password: ENC(Ndfwdx6JxfEvDcZT4FcsZIMWjTToHHS3QlMacIfyakX4+wVrPIM5XtJP8CCexrdh)
      database: ENC(dfPOl5JoYzMHWqNWLtmX+7Rq2CWFfRR9kXEKWWprxtGpuDfmlULnW3XpCN3zkRBr)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 5
          max-active: 5
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: notice@planverse.com
      notice: notice@planverse.com
    host: "{cipher}8857ed5c3ce07d6591cc1856f11dd65d50dc9e6da9ba0f0b97ca33dc6a003f811f20bf4af3d2cdedfae46d030f69afcd35c3a4d399843a55ba417f25736a3677"
    port: 587
    username: "{cipher}fd28a103b54ebf5aa08714e9d92a8edf2a9708cffc58af198793508baf9d28f3438be986f4aedf8c19ce99d16367fae925c4b9d1362be60f60962d2b3967fa175ef674a06f879583c751967fd8294a5771c09e62320d26b4ec0a0a043962219343a588f5e2a047687f6c054055302214e8cb7928c4ac2d394b3d9b8c3b7d8270714c76ff51d258ce6ec1a72ed7fdc118ca36423c5859f0c663453e34de9cdf1a63d6c5dc24cbe3dc1fcc1038405c229f4c389f5a4ca5b0753ad1ff0896dfe138"
    password: "{cipher}5ddcf893c94d7cf35c54addae9e3e6ccef96681cca1558401378185a48fe15f50ced56f6ff0a2140a95887882551ffb4"
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true