server:
  port: "{cipher}da4b0896224d85019673d3437f78d0693dfc26d197c10f483057785e4e911b49"
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  datasource:
    write:
      jdbc-url: ENC(M/upap49DXtCFzkmcNFDWSRTlc+qFEFSBulnYBoTDx63UxHJ5uBAOQnPp/ijldiWjBSwtFVD0O7XaK/Js2u3WxVUcLKDHWwGOxrVh5zE5/Y+XXGzfJqeFS8QCs3H12hyjaD7Av9FoXmGxvvZBRQGIHCJxTb764Dh5XNNAQl4jldpYoYjBcNFUAPtkcmuYNSI)
      username: ENC(ZCwIvvJxJQUAGPPYQIenLJI+diiVdjOmblmLFDfrMd5bP+sNMu3K7csWYbavuK8W)
      password: ENC(snlm5ozS+enJKBhN6oH69p/pqYqJD1Y0r2jBrWCtDXI4GRapzJlYXXfwy+MsQ9En)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 20
      maximum-pool-size: 30
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(WEG9ViOy6CTbGmV/zFlB3BBa41FqRIHio6YCXTFNarJio3jgadb+spQZqQNoXuK40O54liPEPn0E8rAmVVHh7HqEV+OTVv4khSFvOU/3lUxOkKR/Xl+V8sXkeRZg/LwL4Z8Ubz8HWekeEIX7SPviTxpv/HJ/t/aUYkDnCSB8mpZENQBoIWwdcT+pppEooZkJ)
      username: ENC(jPyen/zto4t3D3mAAAbTqnHvFNjr8BcXg76nVKSdDWhdgh7M6aslQC/lUt0Jlwb+)
      password: ENC(lJ2LpROjwSCkoNNzEumiKMpSBjs3xIeKO+/8y/GzHln6n9UJFLT2TkxjTmU3Ma4P)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 200
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul
  data:
    redis:
      username: ENC(vta6tQxUvGyOLBSYJy1BJ10k8JTCGY2p9H/x7tTaYFI+eVlA/R6pRpE8NbDYHhD9)
      password: ENC(NaOk40lEKy0KaXjUp4xDuhdAgOUT4+7rA0f4nGi4uD/ufQs1L6Sfiu+fZ+1ceSn9)
      database: ENC(bt2prOXrXuhPwbigqaYfdKA+x5NfJQKq5HToMvy5IzhL690nCILZMrQAuglZ4rwg)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(0mYuQBk0Q7nnWKWaQfu/MmuAq9RU8lHOqh4qVFw80yLel/SBXKCMmJF34X61YiVX)
        nodes:
          - ENC(9EpDhNopK4LlkD7JaDQminN3qqWyTuLnm7wdjWKt+zx6dJ8qeNsO52sRWd8GHzmh/1lu3XDMpxlG8kY1HVzzFA==)
          - ENC(1qEFIAay5Duk+Mg6tYUu+LCAFrgaFzgJUHIliuwiLwzBHKeFVl1gIiqT6IroLlr6+V4EgyBvDENNW3ULluIoaA==)
          - ENC(2NBOD9CVg85GYOZVTP0Y4BLSqWuddjuQVVQ94d7ZNJ2qMp9X5531CXRXR8XeL0ZEGUr8D7GU3QuQZuoREMGKGA==)
        username: ENC(mlvDe5/L1KDmildIHNxNhmMR5dgCtsCnnPIRKnt7afaoPj0PSPCDSHBN28+LOVc5)
        password: ENC(6DXQw3pAvxQPSi1hHGdCwVrsupCDe+2e7h+sCKU7/PyzupQTdqd6jlWj6yuxp5Ou)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: noreply@planverse.com
      notice: notice@planverse.com
    host: ENC(jDvgYt7eXKSYkVF5sPk0SzqplV2HTi/sWzeWPDoRlP/RIeBGw9kZl9gbS3qh8vOph7g2ZW9xYxdrLvHSf0Z+k/h5cqbL5YWFZ3yNO8wmEN8=)
    port: ENC(5CeX+IWHcf0DBWxM/srpdOLCNdYYLew2Q9Bo/I18UdwvRBha7tY3ufplHZVoWucW)
    username: ENC(1+J4/bnl2P6eIennUgTcsM3VvoWiAFFskDXqiGqcETnx7m50gD0W2WqxNVJhV+vedw3vGwlmD0R5y7mNzzFzMfykwMWytTQdhXFcT16VM+pMJi3lOkstO5OWOt7kuRRDCEZAL04XrTQDSdkU7K2yUTJu3gelgykO+IfZTZkgn+yr+h+VGA1iKc5d8GG9FKgCXZBK7JIoY1r2JTNTIzz9vQcYDAk8zH71EqE/rJYrnMHCIRod649+EAVyi/I8XJlTbVTtiR+zJidcPooEfaQIWQ==)
    password: ENC(tdSpFQkzhlu8wxFC/foRunNZVaLtGkxqsz0U6VQQJdymlcxWWTsbcqHqCNbti/Wq7wYl10oOkY08t9zTli2kRg==)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  aws:
    s3:
      accessKeyId: ENC(YeuFWEMJ/m95k4MyCWbGwfg4V/k4y13SKMKSqW1gbIoo91TzGOqJGkf1kESIWRmAQzqvcfz1iTxkqc92ntiCrrCa3nsf6VtYOQlEJVOx/q4=)
      secretAccessKey: ENC(xxSRUSYizYUC2qlFUCrSf7JPTRzNESL7nlvBPA9KnYfIqJJwgOgEQD1+yzu5/9W4ficjZAOzKXDxi1XWqe2xABzl24QK+/bmj7UXZoxkNNkdJ/fZMRH519y4LLH/poV6xwgWLRKl3aS+JYT2QP9ghg==)
      bucket: ENC(WxcnEIOEh6BjOHHiicLRCUMFKXNkEhAw+H8mNJAAuOwATawPUlK22CCZXDqf8xjp)
      endpoint: ENC(5MVE6I3cGSspjdyq9q5Y+j4vmzH7eghFO9BXuPMLQQmeUTzMy+9Nic6q5pEJHjtaIwpW2+x4V5vbooX2QOUG6wmbFu/n0W81Wfn41IIXJ5yPoq2NmvG+62rdnu/yBKj0oP2JRFspbobF+ZwkpngFbQ==)
  minio:
    accessKeyId: ENC(cCMqZZWl8bEuAXHrQ6GacVRlxQbQ/0kHcH7Li1DW6lYUR77BwHs8N2psyGwWXJmOrgt8VIFj6Y8ZY1p+q8zR9A==)
    secretAccessKey: ENC(jadkeM9yWQps7yRXzOfaDIou2bH3TcYyKQNaSd3kiH4lHBkpsgR231SHLI6sBMl5cuWFxKQjJx7/rG/GC/nJZyJVHHSPA+LoKXAsreQsXwI=)
    bucket: ENC(KiEUFN3xhEpUt4DfLhnd+I1lP6kAMVE1mn+MK8azh5LymYruWkb7gJAry9UhCvvB)
    endpoint: ENC(elOrFzwxhfX2e2Dv5b8eoGb5ModIud3tIyOZDCsJdHdUvFLga73qOaPstJeLWhxHGjghQ3cZ8FS++50ohSkGMw==)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}-${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true