server:
  port: "{cipher}1094924401633dd7f7fdd045c3a92add66d6620c81acf81d3f0a91c4c4cefe78"

spring:
  datasource:
    write:
      jdbc-url: ENC(bReIjam9Sb5VBTo1Ze/bPAenX8W3hkMtOMEyTnsA8r1lXC1qrMAszZjGU5MZiDUGKPofMghrkXQ/QIkTy9a602QwCP261ifmwfodZOJdwVPnILQgzzaH8GDABDsg9ih1oqrCmZPaMs6bbphR3qOWLVQ6n68jsfR51BFJInZZyjcE9Y+g1faVRMiuG2XSaCbzSvZYY+v284AZfUBKHkjBgw==)
      username: ENC(tJgRPUin2YIPmvR3Ock3WarHx31T5gwelRdAKs6Q0XRKx475rDFfM34U43xRUp7L)
      password: ENC(QDP1E7NfuXswvdaHBsLQfqyvaXrgfwX3wLfertznkk6pkNrAC8weq6WhWdXi+XRV)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(Tt9j3dgdEu21ldMuH28XYq4S4bdgpDrFqxcxT83WIu1Qjf0dBPpGlBkCK2/LaKDX)
      username: ENC(By2IvAQ9/qWg6+EbJo9wjb2mbIB19uXmYS51HAhOq3y4bLHeI8KwOafVs4SOb1TiExBq4c9Kw6pQG7YLEUJx1TSQArfzIHqF9HVl29I4LgdLHyxTX9x+fTtS5wN/A3D46Wtw5anwaU1HUgfizDNkmNBjZSNdBnhPCufpvfBTH0d5r6yzfFnf4t13WSit+VX7fW7IpS3k2zA5ScJXQiD0RQ==)
      password: ENC(f20wpDlpoHNhhIvXfl95RRJYJyceEKRXn4E1zdUpk7F5VdV3wNHU8PoyjO0J9Fs2)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ENC(A32vQNlFkXCsSZaiTUTRWgpr2kCQcbUJ5ScJD/GmkonzYSNgTysyZD5sz8zhO8VM)
      port: ENC(KM2nbreUrhkFtIbCSHBrf6Ij5JieuGBKXFA/H67XP2IJyWoa7ZJ4Fk7PGiMO+TR5)

logging:
  level:
    org:
      springframework: info