server:
  port: "{cipher}da4b0896224d85019673d3437f78d0693dfc26d197c10f483057785e4e911b49"
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  datasource:
    write:
      jdbc-url: ENC(9WMUruTXchSaR2Tnt2wYA/LaTQsx4CBUKsv7MGWyYPYzGlmi9V7uYl6Bl8EnGLFL1IkHzX6QUZYsqJW3E675xS+HtZnQ3hJB3qbS2dO5qqrc3+ICiG+Q2oYYe4SlhF64sLQPLa5W7/TKS7wV+cj4Brz0rnAvKHa5ceeqeCA4Hhv+McWXQCscH0AVXZKnI/n8)
      username: ENC(NBY/K2ydNv0eJrJF4PhZvyKAtGLkm84N/WkgnNv2FV55goPJyza96T7vTpTT51sM)
      password: ENC(bfX/3U0MHaYJIRY5NqArWXVDuIqqhrD/UY70sSaIEuO6b992ise7igGE+XCyL/kB)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 20
      maximum-pool-size: 30
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(itgDlBnDJOoH1Uhm6oWcq2YP39trCzMQ+5t6Joq7pHmqOApn8OtW96+by/tiNC0vI4haY0ULx6wM6BlwEa0qQMkAngleD4jbFNjDKqs82AIUBXcS57uM9joI6dwzmKmcKEEYiVMseswNP+DSRchzFH57DZ7dr5Mhl5Efle1LSjYc+A5N2cJxycy+WLj4TJOc)
      username: ENC(3iMVU6TBkhZU/lC0BdsRGLHbyg4CXaYvRiy1Rl3XkWyJaa6u44mzhyEMCe9nO9gU)
      password: ENC(Yuum7T9YOYEaTWyR1g2/xx9aZvh5NSUPN931eBfsyDJMbLmr8BAtDi4tZlkSR3RL)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 200
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul
  data:
    redis:
      username: ENC(K/nkVLbTv+DKQzk3FxeoU4ejsX+qdsCy2VRIhR2sGX5zykWvc8dJTvd44TB7PUkt)
      password: ENC(OI6perkFnU73Fwx4/p7714vQHKSOUz+aDJ9a44ZmPgMRvzGk1QbMNFNZ2CbNm6BC)
      database: ENC(a+Gn1rIL9H6eWRMAez/L4ZhMCPkpSaserK8SmMttg8Dtw51lxNEZ/pY9ZNYLAxp8)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(kjy7QjYxTR18QDqVMKPI6kSFH80iG+oIqCwl6oLdYHDLrO9J+jieps3xM/l6GBgO)
        nodes:
          - ENC(JfAa6ne08wwKeDWwUYgJ4eNVJp42qxPPFFGb2fWNYy9+MZv2FWQMjX+JU6jkRAepMhSO4glmJOBZ5YWcGD6fFw==)
          - ENC(NHkOfb7B3akMhGSbTG7FJHoDyKijHn+Q5buYVm1V8iizS60MVnZK0CW8ImAo8Foi44BpkzAAghUNFkog0PQ9IA==)
          - ENC(biCe83r5obh5h+IZge760JU+Vjb9PSwPYPQjxMzNJ9ZCB5YqNldg8i3aytO48sqjBjFit0hySAs+Ts0q01BXtQ==)
        username: ENC(ZRG4zuooZMwP8H+06RPmUg0cDPinHyYxz5EZ//AfJwCHhek8juAM8sUl402pRjAg)
        password: ENC(iGmttDY/MON4JDm39FrLzftMvRuSghBFn8G7HhhyEjBmD+u5BNJO59yzc/6Iprdx)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: noreply@planverse.com
      notice: notice@planverse.com
    host: ENC(y4GyxmmkOyhSqpPc5e+9V6nJTNrQ3qm6v9vdvNBvCh0Teoepk1Bw0juHxxxTf9qlTZUMEP39i8CWLmphGq/1oEeUgSvn4o2ocqF7B5rI+wM=)
    port: ENC(gc3bc9ueJ8BSsXSiUQzLj5m3uP8ZUMl5Q2OPgG6j6kNoGCL6bMiUdhwiluQ9JNpr)
    username: ENC(HC9OwCPC1/lnVy4zRBZ+n6EqhVsheNXgRl2G/G1T7BmcOIqDup3sTEeLNP1MkZRCe/Zt4fZAk7dOT0ryZa8dByieWQQUq09VJw79ApKePXuIcNyCw9HoypkknIFwtjv3N6foBskyl1pzzyHbpGGm5q+0l5FjxjMNu098mBXtoXF0WtA4BzwhQF+HLlYBIvXyVpmLvDtugIEEDJ1JxWnlWD/b6Vu+DMG8sPXsc/YPOHPft9lueFtzrmx2WBMMTCL/ieO7F62hRQCtM9HKI/Gp5w==)
    password: ENC(spY6H8bn9jWBBwBlV9Cq8bB2XKOOa8RNCU2OF+X68/H0L1xmEEn5TSNHdXaE5KkWXq5smKFZROJLrt+eQIwyeg==)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  aws:
    s3:
      accessKeyId: ENC(tLHqK1DDpdWiHxNfjRGnztMsJtg3hiyj4tZNKtx5FSySmES5DVqLp0zjKFMKBAkIvCoL1dNj/pCXEHvYIMq/MHk6fDMfstCPW42RaUCF2vg=)
      secretAccessKey: ENC(lG/xgqTZQdUCV/DEwroRqujvIMiWQH62bSgukAGSFqIKlNZRRlFJ68MMUcS1f2J35PmG4YYDGcjL71YVatlGjVXlfS4astVIM11uoNN8S4v3wL3xaKh5Tr1J9sJLCqG0zRFZR6OjNH1SkMLuhJMUEw==)
      bucket: ENC(A8Q+jj17EIIkAGTqz8ia9QJTaALcptFqEyaOGMD08p1J6DvRw+MTaY6FQukLWqoO)
      endpoint: ENC(gnrx8fjiJP1p+gD7tpKceu6Rzbftrz7l9WV5Ugf6AikamxKIgrL1lxEuxNqtddPF/3YQ93JKPVPlT183XB4xyoDl+xrL7H+R1VttluBnrm6CJY1b4pxJq1JWYVRYIhpNeQ84Xz3ASDgZ40/2VDGNQA==)
  minio:
    accessKeyId: ENC(HtB46vXPNd6yjhd4XqwRinndhKCbrIt+QbdmPypjeaGDYzq06+yw6nKH6+9l0GplPQouzPDL3RHAu5NpPi9iag==)
    secretAccessKey: ENC(5dtsgyUmHfgMSNNz3l8QLMHnl0TcK62X1w/F9zqISWd+4dNNaGgD2s0qgvfcG7TwMHz4dZibEzqTnEMMIDuSyOpJXeBhAMgFfuMte5WmR3s=)
    bucket: ENC(ACV5cz9AgWT5DI2rkxeNPANx2v5QU3iWKxUNarShECM7GuWGobM970qk3tMUhkxc)
    endpoint: ENC(RRLz9KQ0t+njciVsSJ35BeFf7Tl202+bMWBdgXB475cnKx6+7mtg5Qe72CqCeJxQfahaHmxdxm9a5DszFqWK2Q==)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}-${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true