server:
  port: "{cipher}1094924401633dd7f7fdd045c3a92add66d6620c81acf81d3f0a91c4c4cefe78"
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  datasource:
    write:
      jdbc-url: ENC(b51BdvT4KRHvhzkPJapEMe4xBSnyjJFHM2i0TbWzAvPnFFGQZgxl+/+ljVjNGXwdeyTmsZV6KtsYT5ua7A8ziaSczhzIMaKTCiCnjC2u0KXUyINnD2RA63Cu2W7cMucz+VffwIf/esgfTG3xmkDG9Q8swc0sRbOLw/wgeRTgZU4m2oLDj4o0F4Ic4UCoXYSeD4YbPqoVSf6rfMHucJvMwg==)
      username: ENC(K1UjaVm2WhBKmipgv7kf8sURJ3E/qO+o/v94crA66JOBs89sXSKlM7TRfBsckHVS)
      password: ENC(/rwDby/IxRh42OQNjLR6AFeY3L32aCATwjE0tGCqYSW4ZTuaD94ySHdg31tzyr29)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(F/OC5hJcu94GaAz/ivqZ2lpg6JhLb+WLGeYdP+MeVJprqtg+EUj5urnQl0BA/RELegicA9x8kGhWrJzECwPwbkVC2qSBByc6d53npnQSppO4QfOosVUmIEtlCFNTgzdih9jZF/lLZmYk9CEIfc5NH2dqXRwz3k/g5s9jD1byeEunqDueRg7xZOS6bTTR1hm0Pq1HyF5iI5AhuQtJ+yboWQ==)
      username: ENC(noUFPOrgwfaHjUcMUXpsbt9Tp8Y5L4M2jvV0BxrI7GqUIpxslPKz3SBPtQe3bbkL)
      password: ENC(BN/LtyTNNlQotcob02HHkoj1iAxKHA1TBzAJ1Yx63qGvTQ10xIWmKXpy36nYb4UD)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul
  data:
    redis:
      username: ENC(Pw7HLri/r+Rmv8eyhjonA0llZ7qnczkWAXxjEDBy3KoZUyiNGMd49VpBuiYRTtzQ)
      password: ENC(mLUF/bCBMvWjBVokb+ezQn00h/90yBH3SObBA7qxrTs+riVpx6E0C0AUg86sReTT)
      database: ENC(Fzl5qdVYQ4qyWmHnfSwC/KlOmDiAXYDT0twRL4w/x3pp5sYLQuHcoLUUXReYzdeQ)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(OA8IqCQSrAK7gIgqU5JW/daih9A6cSjnypS8wN/p14Hgw1Ipgj59G06z20t2or0T)
        nodes:
          - ENC(Ra9twjHiDjfAR++eT1rDrHak7J7BfVfQRwV4cwDeqBUeEbwRTzWhGtyhAyi5fyo3g7dsqwh9AnTjingVabsE3Q==)
          - ENC(fPfzsrBq2AMgyZrxI+aAdph9TVLmugo/8pUVsew+i4ZKk3oX846oQNa8uS1j/12GWJBq8QWNaeRkL1/JREGdkQ==)
          - ENC(E2Gg1vxgBOyTLgPA8qJQWrIczaqFjNCRaBVlCXFr2vOD34Pk8GpRijiwAeBkvIGdjmjw1E6qDPGEu3P5i/o0AA==)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: noreply@planverse.com
      notice: notice@planverse.com
    host: ENC(0Jk7s9gE7MXblDNNRsiKUm+Eqypoy//3V5GS0BXAXDFeRUFCIkhJcm/1c+Z/1mjr7Yg+0wilV8faFi6cl75jCaP5+pDVQW9IEaq7wJD37c0=)
    port: ENC(VYRCEkZqFz0V1bx6fbmQDe5pfP+ywdVgf5mhh96UbbHJczN7tG6jO1GSqYoaBjUu)
    username: ENC(40vQULwiYkJVd9Jd5NqG10vlSykYMASvuS/quVDVadp6MCPrdZBVsb47D19eypdCfaNI3HzQ8cYT99gmXc6arhx2bRUEoWHRTAgW/hlvlGekbVmJH5ZMpUug74brDC1qMOxwT+BtDuTL36oC2YAL0oyHnqey6sXZOV9SAbhFzPel81fMcJ+f7hHBtuU40o2/RBkjJ2VupSW+7SGxxERAvL1sXbQamfGtxPSnzfTYswKR+JI5InqbAXz4AYA9RsyhJZzF/qbuZPJi1GEx2vDeqg==)
    password: ENC(0YIUVpa5hmT6Suy3vjKeo7vaLHJKtbNr9ws3tdMSCanS7Jq+On5RGAjkfGABk/78epU/B1Ms3Io/xYjqo+3+qg==)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  aws:
    s3:
      accessKeyId: ENC(aIl6HT4VnDp/GDEg4ZyhO5MuU/lQV+rGTX/YoxUMNSAxtFYaMiMDIy1KqTomnlY1lEcf+1/5gbidiprNNHpNfrClkIAF2TpuiUmBvI7scdU=)
      secretAccessKey: ENC(82wQ/6FVGnxT80vvtLPD461StxyKwTAA8vo6bvAebdPDrUp96CY/vKokRcSDxo9VZoeeUXWTA3AFneCn55IcBYO63IWmPCh2HR9al47u/sS/3+fWwSLHqKr2em+uzBasDRsEUSVIvuKY/kTC9bDQvg==)
      bucket: ENC(PXsbqsB/A/Crv7MFNhxIfQv27T7UYHWC252raNy/TYqJ85ztORwp0mzXnFM8Y+Va)
      endpoint: ENC(Y3C0zRbVZZOHktMxMWJLwtWzK5PwEnj0pfwnCPYChkp5LcR8D6LS2NeTqesNApkSKa1AKa13jokL2qbuAOMJ71Pu6IM1hWuqc6EKeRONPLPmT+zA3OPwrEjSzl7i7m+WQtuNEv8NCfKyZUPW2xebug==)
  minio:
    accessKeyId: ENC(Zc6/Xj1vG38429VsZlHzC7JnScNsuEeNZkJGxxWP6lW96Qx7e569RhsKx9QX6x5nNk6oTaTTq9Owyjd0Smrxdg==)
    secretAccessKey: ENC(89/K1bJNtpTb/qTbWVHZXAxuR8Et+M7hFEj6QvfLBbt3/5y1OkH2S11X/b65sXQ/ESnkPSWZiUGRzSdmDLnzdmtH8+HfPbK4OFhb66cv5LQ=)
    bucket: ENC(Gb5O+u2fXs8Owm0scMldMRNAw5qmK2qEdWLfyme/GnaLH8OMYdDBWEhLYAufj+8g)
    endpoint: ENC(yU0sQBpDPSPvBGZksILZxOD94uM/4eJ1hZxG9YLeMxYH5Z4IT6gsl9N6HuRb4OgPqtMsRQUZW6Nq7LkTfPCKnA==)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}-${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true