server:
  port: "{cipher}bf956972a5490bbf9833ef07b54c0a93b675a7350bb5c531c87ea223673dcf0e"
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  datasource:
    write:
      jdbc-url: ENC(imrvU0w83Hy6ARsS+MvZXDDH4hDJiMUyfojsjttVGpjy04mBLT7+dvlhrOwpLT/3xvtuMVEnydfRpGvcquLpgbSDMmwrf09g6Xz7wZ7y5fkIJZWXXk8wqqvShqRwYtlK0K0W0Q1Cik5x+aiqKjzLEiiOGjYndtduzC3TPS5Nid/tjgvsjBKazHG1T7Twprxm)
      username: ENC(Y+cGc6vxxPKa0EUm7vgk0DBkAqERYR6ElfhybJLE2KsfGUHTWsKzI7U/WtktsEW6)
      password: ENC(1jp4v03NuABM/qlzU77dLCGIyoRG76uHQ7RomUwTcfS3vDf7hHyWNt5LCbNfoI1I)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(qAy3/1dAnRjG/9PYEss1fcG+tEqlxQWelZJHUeAmJaoOnDAK3d4WdRHmJtM/+Hxya8GhmVxnJ8+3v5F8shXe9iO/3FVaRdPiRqjdTpYd7Ch0WTdwEbjepgsZgStJuFkRoMH8W8C6TQyYA7m0HOT/XPIyuPM1LddjZzmHxebYJ/O3ejclXae0qgSBNeRiY2u6)
      username: ENC(t+srkltVDR0Ijc0JgNooyhac1635h4tUm6LRDyAHOWzBQwROhFs1uSq7q7tHx29Q)
      password: ENC(UuTG4zQ6M4NQaHH5eZSPel3cyuAfPE/H0f/MAIGb5zifKPmsiN7IunDhhhLCN2Go)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul
  data:
    redis:
      username: ENC(73RD9rOZw2zfYgNFXq5OPUZQQWjQ/tisKXBIuedzi1ij3STln4sL3E5LF2rWwLpl)
      password: ENC(rnXlKUi2ftbdbaoF4Ym/cZDjFuFAW+UzNUwIwX1WHfG0qeQHyvdGcboE2eNaAwb9)
      database: ENC(4YSrcAvcoJgvkhKduVvaM4m+1J6OszJGMUBrwTLLivXOcMl4qfkWldvmavN8oIy5)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(VgzFP7RGuI2zsyIeM2Bk9loOQFvv5J3iiCGa6Ok8XW1QhsOBybYT9tOIue8+gVpg)
        nodes:
          - ENC(UlSQHkZfjcdurHSXi1ZiRF6lLB8eE01YQj+fGBxHLDONscpkDeRMbFiHPwQ/8BPjBlU2E9g61R6z2seeeSNA/g==)
          - ENC(fsRSrf9KAbo5s3gm8N1ITIW0XtJy7GMcIqiGCH6mcNyC4qppCclvIyjBOOkCWiPKfTG6TZCre2oY814qqOdVbw==)
          - ENC(FGrtWsOXT0L/5HiEhXT4DoBX0aOUHG2wb2xut+0G66IwZloFhY6tFrhNiYzuR7tC8fpbWD9amp8Zi4CQrmB6iA==)
        username: ENC(3oSh8p2QywyyjPcZFFnMv3mX1/GgllgJh5BtmnUeDB33RGDAa3K3fSdXkipiz4ym)
        password: ENC(XclVRdktxb4mnrlX0R9e3/Mk4dGNTptTzEyNeFi407z67JAACVM1fWw3zuYKi4km)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: noreply@planverse.com
      notice: notice@planverse.com
    host: ENC(Y/7HnGJfyZYmxqPcq2XcRjGZlvOvASm86xmVjQQTW/vuvYrapmHZfMy6gVuPvZje+aaQ9Uo9j8WXC0wuNdfpznkG+E3yS1p8T23PaopEndo=)
    port: ENC(e8RWVTL9SWWM5brOtzuWoAcbpM7vFDqGq9x0PXau9mTWjp3giQuUjASZRAE8BL62)
    username: ENC(N6T6PljFBqKOQDdmz0gPrJcPIQPLAdzq1CB/rvZ0qx+9pShDEXN0fICEwYifVNxD9Rp9YkpA2GZO2aNXtjZiyxZyB2w4lGAHXsp1yXO0Y5kJxGAbsXv04QPBtH3ZxezhIFB2ucOGxe7EXsBIushQcZK+TqU40CpqbDWSHHt6Jgdf00yKzItfCE9iFpnWTp6Pf2Ie8xbIIqQtZLV4cf/+zS3Yx8yw7hUXxOZA0zIPu4VR6hjC6ZB5I1l5XpN1udTzw1QxjHyYp2cRR9eCD0Yx9Q==)
    password: ENC(sn2vT574LR7o7Oomtyr0ZTlHJaSE1Q6u5kkjgfKh2qLyR3HsgUlBa6I1RqvmYnfUNObWZlmEbpPWh0e1O8g5ig==)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  aws:
    s3:
      accessKeyId: ENC(rdjeufaTzIAsNqvFFdqtWECMeBQ7xl3a7TI5bOyDbpaAiURNRdo0f8KbBjrxwJMyLqEs8kBjuM2KEnVqgAAWS29tG5EqlXzopZZtDEwWed4=)
      secretAccessKey: ENC(JQIXQOA9i8ojojbCrw6z3wdbafJUY/7b1Ir+GSoqmYH6wbzEuEwayhq3gi15+BrF/pjdrndwlBt5OCA4fike+tDf6IKGSngyujT1zAMkgEGpGaXHe5AQDJegHiypCizRgN71lgeLuTVpnIru0s1n8Q==)
      bucket: ENC(EFZh8ITEQ3sIiHDCrl6+4EgMa+YVJlZBi1JVbH+Y8v+Amf0FY2kh2IgDubmsK+7M)
      endpoint: ENC(M38nrLfYwtQ3iuUF09fg6qOUTy7jzts9ije3je736I85QTMJI9a2x7+CogZcTrHfecuJsf++OFIIRBGPi24i5PG8xXq+PhAVqIoSQ6qldgdBTEX4M5R7KptgZKB0z7eTNblP2IziOs8K4q9yj2MsgQ==)
  minio:
    accessKeyId: ENC(lgKs0DBW0n3SGWuOXm2gHhDBBXZ8mfu82No29YH7k5Y/NetQ/3ABz+jB1n9S1M6fYDwu9N7Yhbp2dj6irs1gWw==)
    secretAccessKey: ENC(Fkq4HkKhpO8zoD5LI3M03w2CM+bhKmSNtq875k6eRiIWwOGHDv5LFUlMS+fGvzhiGzNvTByziGSjLfp5bu0tFLD8gWiewcAFApzrXE1mYos=)
    bucket: ENC(JDHSyCt3QmUyYbiqc44+FuE7LimMpkDg9NIjT7D8/rOKEeDvsuHdc4n/NjAY7AC8)
    endpoint: ENC(lwasPyh5/FjCT7UsdG87n9zz1015sGdJA4gfYSY4A+2EBkzUzSMufFel+SEg4tAuRneN1jfGM9KfnwGTG27wBA==)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}-${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true