server:
  port: "{cipher}1094924401633dd7f7fdd045c3a92add66d6620c81acf81d3f0a91c4c4cefe78"
  servlet:
    context-path: /api/v1/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 600m
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
        max-age: 600m
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  datasource:
    write:
      jdbc-url: ENC(ngUlT9ftwhNZ4nCt4IM6A5mSsO0guJPnNp2IrcurDcfM07TDbGlR+jJI77ej1Cf9lK85NLSze9hN2y/kgJon7lAjXNNRr7n+23fVrUrYheXrkLxS36bvTQryqKhS5G0PjiKt1UtrYe6FWhA1eq/nvnLhVq31J4wcc5VpIKOCFZ65NIBMo/zMXEpBLayoLlZvt09fcgFw05alFESdumJ0KQ==)
      username: ENC(kNiLzdVpLJiLwh/7OR5r23MsCmBUts48WkIm7oTpwvrgGd8ALZRjcFGW1S2fa5ZH)
      password: ENC(n2YRNNe+ms54D4SPt6+1xrjvmwv2pHktJAb2JadygVeFgv4f5SbPeIVSX/VDYX9Y)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(Cy5KlNCEMuVtb/7w9HSkM25HZVX99jXoM9mW0KC0zn1jGVuLG5vNp7IktDZDbsE4MXvuMdtWK+G61KQJALgFVXcGbCgJItIVK58OYjSf3MgHNLUftwlFviGxlDJndyBYtAzDLDalDn+/ZbAFPEX13KUAKAM6dJziV32KgkXpZIzSINAD7YImn0y/I05Tl6D4VeZS9dvvE+eAG6XmycFEBw==)
      username: ENC(LMzIeHuSwKHH0yykfz4ytSAazTqnWpta85ShvceGYd1/QcIlPL4H8MHDh62I3Cv5)
      password: ENC(7qBpXcMM5onUOa99t8pWJnYHGlTGUS4PjXin2Q2px+iOzKz8V5gAcidxOoD7jDxp)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
          time_zone: Asia/Seoul
  data:
    redis:
      username: ENC(oD3CWcYVBDSwe+D5lbh1eCoVunO04QIW4fzBoTNK+NftG8VNgFLJkzLLcxcOhceL)
      password: ENC(i4+Y1NQS8+JO3S2CP7qr/iBs0KFNyHe/t9nsQRu6nDguGkKXs5t91vufbZUE9dda)
      database: ENC(2OHuRwWcF55R0tcRZhz34Dh1mFZqT/YxVlIm9IgvxQs/DHNeR1W/9wyVekvt8ozK)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 10
          max-active: 10
      sentinel:
        master: ENC(iMUsmPN1THIDiSeuo7op2V/Q/qQNz/AdN8q/0X0ggnwqM3wnWtVOHrCpvvluLYTX)
        nodes:
          - ENC(MOv9V0pSmq/eTUFsRaLz2Hld6SCiiN3T4HKJgWT2keAGJgHs7Ws90UKkuDBIDuidUavU2mc6Q/8+C6m0Z1YYcA==)
          - ENC(woBI6fJjyAirz3blYVRmctR0AR1ADDCkmict+9y4sXWyHMYRR/7K9G78PG0nGn30Mfhh/u+1M6SbjE09B/vgVg==)
          - ENC(heaeQGDJcgshDRj6PHAH3dzevMEGcv6YuKQxo0+oV2eEI5vW0udlxc5WdjuiIjVjGvQIGpB6gODO4rEcKZBrYA==)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: noreply@planverse.com
      notice: notice@planverse.com
    host: ENC(GG0MVrUzYh17Ljghqq1mQi9LGjWQqPiLMc5QurrIzDeQ2MhQgYhb834JzO5srLKVuiBiy9psa55Mxk5RmH4H9XekgYBUNRNXPZHJzXPDp3U=)
    port: ENC(hAWVT6PsmnIQtvKM8F97+Ze+lP4mCBLnskvXQ7Gze/DjGVaKRjNfBc1/qKrJnwJU)
    username: ENC(8I175c/hO/nON+V9DBLg5TtN8zhF4BUCfwWV/5N79yiBHOgc09133QCQHgex1lgufUM2t/1hRabU6HILPNCLuRUFhZ9Ar2MrF6MpmhORurG3JHBok2lsi1Qq1q0vhhuDMB4BeTFmieZ4eulVD73qlzJ/uMd1v2GC1QHLR/cK0csS09FPRM6qeHwJS4oCwTOo+EsKKUpSH03d8uyv6TjY4YxCHJlaaVPDVEudWIJbbyyyneY2STar8gjmH62nU4eXMxxRssZ5+UT2NxBOpIoxZA==)
    password: ENC(6VDM5kr/LakkLbrCi45xOs5LVWN0rgfRTcRFw7VFtGZJ0hESdUWN/LxH2vLBgCIgrQVMhUrba4oP1TzkIpPzEg==)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
  aws:
    s3:
      accessKeyId: ENC(xxwG9bHhGRB1RB0NduHqxJHUxgTA0/N9zpE5SWXwHUdmY6hsMyvYc+lO8YuXvpwgtKMPvIjx/HAgN35poqzFngZ/0RAY9I8h+ChvgZqPlZs=)
      secretAccessKey: ENC(JGTSRx6O3WlFAgY86yJcQkEgAvFzvM3VFcLlh9w2tM29R2oX70d+DeMZwPVrUdNH//VmnevROR0rB9+OUApwSo/AaQy36e1D35/F9Sk4rSgquMdInMuXF2//RGULGA+EnA7wl783aY/VcChP/nMUfg==)
      bucket: ENC(EpuJ2NveTlzKVkdwi+nasKfM07odlw12AmB7VKlX/RxixYpj3rAifo1IZywAdxNR)
      endpoint: ENC(O2TidmUOyyGYV5Esk0BK4w0PtH9Rlj78sNQHL/+jtWOkp2qPuz7CDqjQvx0brYzruADsfB+qRAhALBMZpLOyS7oTNLKu7/Srushf2XDX9GgrL+CBx1YaDcPVctgbgil0tnOLe5s8Q9URnI+iy2L2Gw==)
  minio:
    accessKeyId: ENC(B6nbtpzZhtem3YALzVis0NOYD+zDUOpYKnD02+laHTSUakwWYpNiGdWqI5riGOqRGomhA+NYlxs/U9FTdWu3ng==)
    secretAccessKey: ENC(G3aimJJnazdt1lM1WtAwQcgWuR/nHywEEmQ1w1ExZJTYjCGEIIP9Etn6zNXweY/IQmYTjzNYfKYCNql9DqiaM1DTwuGXzRVlJAmvN0OsoLY=)
    bucket: ENC(RWL8q8a87jVPfyDBwsxu9D6PNYeaXjd6k+k9mFmQ9FNvBZCMjnEZmgzCCsBl0p/f)
    endpoint: ENC(GG/ORQoTi+0x3Hrwv0qUSd6VBGop27ZAo2asDReJHNkSMcwu5HCWPRrQSP04XVHut7+sytVnu6vuK09OaLbA6w==)

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: none
    health:
      show-details: always
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}-${spring.profiles.active}
  prometheus:
    metrics:
      export:
        enabled: true