server:
  port: "{cipher}bf956972a5490bbf9833ef07b54c0a93b675a7350bb5c531c87ea223673dcf0e"

spring:
  datasource:
    write:
      jdbc-url: ENC(tYTGlPXMkcNcvePL/obRXg6ay13SRyDktie/KsxcmB1M94Mw6DawhggYU6t3AllYnXk7/O3CcMZti9NMu9Rqa4mYzOUmKzzoHUuf4qeS3rAg/OsRNRejpPojCdYLmCH3KwSldlod7T13LbHPiSm0zjMtmRdVO2cokrL5WU9etlaABKu2Pa1EGXPxgULrpOC4Q19h5FluV62CNlwXILC2vw==)
      username: ENC(NE6lbs2Sz/f3ipAiDyT29jUnMRfaHpS9LubMcOyYwB75hFILYpmq6qm0HOzKDDtC)
      password: ENC(z9yFWhYKM1m0pI/jsV/9Rw8GqIe243De/SlBg+ukRLckLIWQi24PmNDUjSuj61n4)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(T1mb1DbJTYItHr3VzjPgP+pDPzeAV+23CkmcBJN0rVREAHkLY+2oRTdvWSNdCd5LiKAoVfthJxxTTSqBHj7nqZEdE3qauDAteMYVE5/19MfN80R3uriIBsezoxi2xC6HRLNtY+EqnsKHCBYr6Oe4z7H/idtE6C8RBqR26hpAYJ8k269GsM+M70GU1jaMCIMH5eKoYNyT1pzTdfCUZyo/BQ==)
      username: ENC(dCyfuj6NuUXe9gsLyP+GaXoCEU7qNKuT2wObatHue7bttfEFHEHPrbzUViwxMbzM)
      password: ENC(q9yRmPASGFgh99SqRm77LM14glpu6b0AGW2eefbC3vtFrbsaSkX/zjdJ9x7nCxxE)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ENC(4vi/XFYZOgd6RuU4LDj64LoW8Of5xCPXsltxdf1k+R9XrVsw9IIBpmEmKctOs2SrtYqhBU1SLuxr7gZfGKH/iw==)
      port: ENC(IFYmxg/VN49du5PP7nXwjxGako+k/jGI1wtdPBrzgpaIR8aGZakieNybePRhahsZ)
      lettuce:
        pool:
          min-idle: 3
          max-idle: 5
          max-active: 5
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    sender:
      noreply: notice@planverse.com
      notice: notice@planverse.com
    host: "{cipher}8857ed5c3ce07d6591cc1856f11dd65d50dc9e6da9ba0f0b97ca33dc6a003f811f20bf4af3d2cdedfae46d030f69afcd35c3a4d399843a55ba417f25736a3677"
    port: 587
    username: "{cipher}fd28a103b54ebf5aa08714e9d92a8edf2a9708cffc58af198793508baf9d28f3438be986f4aedf8c19ce99d16367fae925c4b9d1362be60f60962d2b3967fa175ef674a06f879583c751967fd8294a5771c09e62320d26b4ec0a0a043962219343a588f5e2a047687f6c054055302214e8cb7928c4ac2d394b3d9b8c3b7d8270714c76ff51d258ce6ec1a72ed7fdc118ca36423c5859f0c663453e34de9cdf1a63d6c5dc24cbe3dc1fcc1038405c229f4c389f5a4ca5b0753ad1ff0896dfe138"
    password: "{cipher}5ddcf893c94d7cf35c54addae9e3e6ccef96681cca1558401378185a48fe15f50ced56f6ff0a2140a95887882551ffb4"
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true