server:
  port: "{cipher}1094924401633dd7f7fdd045c3a92add66d6620c81acf81d3f0a91c4c4cefe78"

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    write:
      jdbc-url: ENC(vkQA4ctVoPw8oYuQ0DH2SjznFqHlJle9gP/MTENnzbKeUrE1f/cnXHLPaFUsX7+xfq0s185urO9EbII86XxP9/J3GimFw9fsy9GSHbKw+UJFKPa6RuzuxqMu+y4/u/XVLnOujoPNZK5yW9cEGHzkWO1Hddov6zLUE7r1Ovgoip7tLiIWHXqkqJ0wrfPTZerd0DEySz/VpVR/7NUsBr+b8A==)
      username: ENC(JmWiSsvxi7JauOh0wOGYsSUtcAEy8JfN3j7VtaVMdMWIyh/ogQXyp+EtJ1PHMuBq)
      password: ENC(mq9zHDMMwatOSUXgodxafCbmWmqasNaJAbshxiPXSi7JSzEa1e80mNsBl76IweUc)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT NOW()
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(9wyJ0pol7ui4EP48G7E9Jl1QORG5MGrJMvTqXuOk/Tsv8MiPYrAkMyiKBL/MphHg)
      username: ENC(kWi9+heRgRZ9GvDP6nvcbdTW5X35GtLUJxrs4ikCOBGC4IFgqwm3rdhjFPKBkNgxrSDLwO2Lrj8iW04bfhjssrYkIjvv+vS1w1xaI+8OavcxWE/hbTjne8cSRxC3r98JXMGKoTG+T3CqeudxYXXrnMGYMIvuC2x/VtZTGRXI+PwtTDjz5qnwQuP0UtDi2Xs/BrPJkKXae9q3+3NSgiankQ==)
      password: ENC(QKtDfXeusP1CDOmZIcw5wIkNoM3QhIIdGB0gTHQ7HT6dN+FsCtt/95sH6u4g72xu)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT NOW()
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ENC(l0om1A6Z58253F5m/e5TED//O5wpzpxtk3dMoJ27vayCSMMtnLRoXanauVaXzUYKmgopZYELoslcbuf9vhm1Fg==)
      port: ENC(9i5k/HSfvWIUmSd8D3Z9Kqk8gO2D+TVTDk7uqYdg5I+kruVZ3AgY1EybGWxGh2SB)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org:
      springframework: info