server:
  port: "{cipher}1094924401633dd7f7fdd045c3a92add66d6620c81acf81d3f0a91c4c4cefe78"

spring:
  datasource:
    write:
      jdbc-url: ENC(f2QxeEDSDJlAepHS5Xh85FltK0Ncre3bOA7fQXJCIgBt/5OxdYAriz/V6SEDPtAz6xCigUFz6ZgRMlwOJ95M/qTbCXdgratF5hOfxhnkbzCnqEVl83uCR6LG4iSBaMKVuHK/QoJBsc7bBJwZwIGKT8UKSVtFm6NmD+VaEhHm5rIdHeA5/+76qRvwfYNqcB0P)
      username: ENC(Y+g+Mncoi5VdJ3bcMY7dQI6FLwzygc3XbVHDNwluE87Yft8h6FO2PhaAqxIxaxP/)
      password: ENC(sq8m1b5/wU1bQAfYj4g5dmPyO+IhgwGPdMY+jVAXQpbE675+UoYNtpqEcfyUYwwq)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 10
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      pool-name: WRITE-POOL
    read:
      jdbc-url: ENC(RoX33VppsQdgnBF/GrLK1L4NluzeZFT4ZgG9tWINZcaf8bxFjykR4zxaCKYBlVj7)
      username: ENC(Kn8VKrW8c8SOJ/Ix8AW6rt+C/7caZjkRszho2tOgpM4LBjYmhxazNaZRhu/eQgrWl0SQZK0BwQ/Q2aA5KdQ3p1EN+c0MTdbgF2YWe17sSsf9kn0uORjcZ00YnvXlYhO/hJbiC4I9WTb5B7v4byAaQVBcnqxn8ETwlpKJHcmcGFeadLxAjTzaVYo3GSEGevSx)
      password: ENC(XVd16EYIHbLk5SddqGlx6DFO0Cwkd30mz1CgzCb3eTkRo194pYEZ+3idCqE7t5hX)
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      pool-name: READ-POOL
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
          order_inserts: true
          order_updates: true
  data:
    redis:
      url: ENC(4S4inZ1jtdfQsNRXzSQAQ+4nhuU3T/pijPeolbZ/gAadE6efcc/K10zdDGxRT0cTlcJcmbE4qWVKXvZT7/cj1A==)
      port: ENC(m85SN+ivCps/f785XBuXrdt1rFqMtH9Cz+i0UKIY1F8+6Df77URhIFgTmvF5GrPJ)
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org:
      springframework: info